apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  template:
      metadata:
        labels:
          app: helloworld
      spec:
        containers:
          - name: web
            image: jolestar/go-probe:v0.1
            ports:
              - name: web
                containerPort: 80
                protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: helloworld
  type: NodePort
